### ISSUE TITLE
Slow performance with more than 100 gists

### ISSUE THREAD

**Issue by kinduff** [NdoleStudio/gist-cleaner#10]
I have a very large list of gists that I need to clean up, around 250. The app is very useful but I need to wait a long time before deleting something since it needs to load the gist preview.

It would be nice to be able to toggle it on or off, or by default, be allowed to have no preview at all.

**Comment by AchoArnold** [comment]
@kinduff 
I think the code has some built-in limit to only get the first 50 gists, are you seeing performance issues?
