### ISSUE TITLE
avoid panics, handle errors as graceful as possible

### ISSUE THREAD

**Issue by xackery** [NdoleStudio/gist-cleaner#4]
https://github.com/NdoleStudio/gist-cleaner/blob/1fbe5ff283bb44af04f668b7660c7a06f495d7e8/backend/main.go#L303

panics are "red alert" kill situations, and stops execution of the program at this point, with no real ideal way to recover. It is suggested to handle errors as elegantly as possible so you can recover to whatever sensible state you can, and finalize your situation. 

I'm.. not very familiar with this sentry SDK (and it's intentions), so how you best integrate middleware to intelligently handle your errors is something I didn't dive into, but I recommend reading this: https://dave.cheney.net/2016/04/27/dont-just-check-errors-handle-them-gracefully

Ways to wrap errors described here: https://blog.golang.org/go1.13-errors 

Hope this is insightful for learning more about go. :)

**Comment by xackery** [comment]
Read a little more into your stack.. while sentry/zeit does help with error handling, I think the panic is shooting yourself in the foot for testing and general decoupling.. since your entry point for code is basically the Handler() function, you may want to write an initializer, and a response handler function that you can share across all your endpoint handlers to ensure errors are gracefully assessed and simplify boilerplate. 

Above still applies, that is. I wouldn't use the logError() style, and instead actually return the error with any applicable context data wrapped to be unwrapped for verbose error tracking in testing, on sentry, and in prod

**Comment by AchoArnold** [comment]
Thanks much for those articles @xackery. I've definitely learned more about error handling in golang.
